global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

alerting:

scrape_configs:
  - job_name: "graph-node-metrics"
    static_configs:
      - targets:
          [
            "graph-index-node-1:8040",
            "graph-index-node-2:8040",
            "graph-query-node-1:8040",
          ]
