global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

alerting:

scrape_configs:
  - job_name: "graph-node-gnosis"
    static_configs:
      - targets: ["index-node:8040", "query-node:8040"]
  - job_name: "indexer"
    static_configs:
      - targets: ["indexer-service:7300"]
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: "node-exporter"
    static_configs:
      - targets:
          ["indexer-gnosis_node-exporter:9100", "indexer_node-exporter:9100"]
