global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

alerting:

scrape_configs:
  - job_name: "graph-node-gnosis"
    static_configs:
      - targets:
          ["indexer-gnosis_index-node:8040", "indexer-gnosis_query-node:8040"]

  - job_name: "traefik"
    static_configs:
      - targets:
          - "traefik:8080"
